### ISSUE TITLE
D(:,t)=sum((X-c(t,:)).^2,2);

### ISSUE THREAD

**Issue by zhLawliet** [pravin1390/FastHDFilter#1]
错误使用  - 
矩阵维度必须一致。

出错 kmeans_cluster (line 31)
          D(:,t)=sum((X-c(t,:)).^2,2);

出错 kmeans_recursive (line 12)
[minCentre,Centretemp,newdistvect]=kmeans_cluster(X);       % Performing K means clustering

出错 bilaterallHSdenoise (line 38)
Centre=kmeans_recursive(Ares,Cluster);

[n,m]=size(X);
c=zeros(2,m);
D=zeros(n,2);
for t=1:2
          D(:,t)=sum((X-c(t,:)).^2,2);
end

**Comment by RoyiAvital** [comment]
Does this code match [Fast High Dimensional Kernel Filtering](https://arxiv.org/abs/1901.06112)?

**Comment by pravin1390** [comment]
Sorry for the delay . Can you give more details as what is the dimension of Ares in Centre=kmeans_recursive(Ares,Cluster); ?

**Comment by pravin1390** [comment]
@RoyiAvital. Yes. Both codes are entirely different algorithms. Both gives good results. This TIP code on average performs better but the other paper on kernel filtering has stronger theoretical guarantees

**Comment by PoojaVineeth** [comment]
Im getting an error that the matrix dimensions are not matching for the operator -
